# Generated by Django 5.1.3 on 2025-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título descriptivo de la tarea",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la tarea (opcional)",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baja"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-created_at"],
            },
        ),
    ]
